// Auto-generated by the Clone tool — fake data for preview only.
// The real backend returns 404 for this game's /api/frontend/* routes;
// these fallbacks let the news tab render something instead of nothing.

export interface FakeCategory {
  id: number;
  title: string;
  slug: string;
}

export interface FakePost {
  id: number;
  title: string;
  slug: string;
  category_id: number;
  created_at: string;
  content: string;
}

export const FAKE_CATEGORIES: FakeCategory[] = [
  { id: 1, title: 'Tin Tức', slug: 'tin-tuc' },
  { id: 2, title: 'Sự Kiện', slug: 'su-kien' },
  { id: 3, title: 'Cập Nhật', slug: 'cap-nhat' },
];

export const FAKE_POSTS: FakePost[] = [
  {
    id: 1,
    title: 'Phượng Hoàng Tru Tiên chính thức mở cửa máy chủ mới',
    slug: 'mo-cua-may-chu-moi',
    category_id: 1,
    created_at: '2026-09-20T09:00:00.000Z',
    content:
      '<p>[Dữ liệu demo — placeholder xem giao diện] Máy chủ mới chính thức khai mở, tân thủ nhận ngay quà chào mừng khủng.</p>',
  },
  {
    id: 2,
    title: 'Sự kiện nạp đầu tiên x3 giá trị',
    slug: 'nap-dau-x3',
    category_id: 2,
    created_at: '2026-09-18T09:00:00.000Z',
    content:
      '<p>[Dữ liệu demo] Nạp lần đầu nhận ngay x3 giá trị thẻ nạp, áp dụng đến hết tuần.</p>',
  },
  {
    id: 3,
    title: 'Cập nhật phiên bản 2.0 — Thiên Cơ Các',
    slug: 'cap-nhat-2-0',
    category_id: 3,
    created_at: '2026-09-15T09:00:00.000Z',
    content:
      '<p>[Dữ liệu demo] Phiên bản mới bổ sung tính năng Thiên Cơ Các cùng loạt trang bị mới.</p>',
  },
  {
    id: 4,
    title: 'Giải đấu Tông Môn Tranh Bá mùa 3',
    slug: 'giai-dau-tong-mon-3',
    category_id: 2,
    created_at: '2026-09-10T09:00:00.000Z',
    content:
      '<p>[Dữ liệu demo] Đăng ký giải đấu Tông Môn Tranh Bá mùa 3, tổng giải thưởng lên đến 100 triệu đồng.</p>',
  },
  {
    id: 5,
    title: 'Hướng dẫn tân thủ 7 ngày đầu',
    slug: 'huong-dan-tan-thu',
    category_id: 1,
    created_at: '2026-09-05T09:00:00.000Z',
    content:
      '<p>[Dữ liệu demo] Lộ trình phát triển nhân vật tối ưu trong 7 ngày đầu gia nhập.</p>',
  },
  {
    id: 6,
    title: 'Bảo trì định kỳ và lộ trình phát triển',
    slug: 'bao-tri-dinh-ky',
    category_id: 3,
    created_at: '2026-09-01T09:00:00.000Z',
    content:
      '<p>[Dữ liệu demo] Thông báo lịch bảo trì định kỳ hàng tuần và các nội dung sắp ra mắt.</p>',
  },
];

// Generated at the same 560x450 aspect ratio NewsMainSlider's <img> declares
// (it has no width class, so it renders at the source image's own intrinsic
// size — an unrelated real asset here previously mismatched the fixed-size
// news panel next to it).
export const FAKE_SLIDES = [
  { image: '/assets/_fake/slide-1.png', title: 'Slide demo 1', link: '#' },
  { image: '/assets/_fake/slide-2.png', title: 'Slide demo 2', link: '#' },
  { image: '/assets/_fake/slide-3.png', title: 'Slide demo 3', link: '#' },
];

export function getFakePostBySlug(slug: string) {
  const post = FAKE_POSTS.find((p) => p.slug === slug);
  if (!post) return null;
  const category = FAKE_CATEGORIES.find((c) => c.id === post.category_id);
  return { ...post, category };
}
